# Generated by Django 4.2.6 on 2023-11-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_collection_post_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='collection',
            new_name='category',
        ),
    ]
