# Generated by Django 4.2.6 on 2023-11-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_author_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
