# Generated by Django 4.2.7 on 2023-11-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
