# Generated by Django 4.2.7 on 2023-11-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_category_title_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='AuthorProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
    ]
