# Generated by Django 4.2.7 on 2023-11-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_author_profile_image_authorprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.DeleteModel(
            name='AuthorProfileImage',
        ),
    ]
