# Generated by Django 4.2.7 on 2023-11-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_authorsocialmedia_socialmediaurl_like_author_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
