# Generated by Django 4.2.7 on 2023-11-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
