# Generated by Django 4.2.7 on 2023-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsocialmedia',
            name='social_media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorsocialmedia',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SocialMediaURL',
        ),
    ]
