# Generated by Django 4.2.7 on 2023-11-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_authorsocialmedia_social_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsocialmedia',
            name='social_media_url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='authorsocialmedia',
            name='website_url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
