# Generated by Django 4.2.7 on 2023-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_authorsocialmedia_social_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social_media_url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='website_url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.DeleteModel(
            name='AuthorSocialMedia',
        ),
    ]
