# Generated by Django 4.2.7 on 2023-11-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_post_likes_post_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
