# Generated by Django 4.2.7 on 2023-11-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
