# Generated by Django 4.2.7 on 2023-11-11 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_post_author'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorreviews', to='app.author'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postreviews', to='app.post'),
        ),
    ]
