# Generated by Django 4.2.7 on 2023-11-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('review', '0002_alter_authorreview_author_alter_postreview_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postreviews', to='posts.post'),
        ),
    ]
